### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by faradayfan** [chgdev/express-service-template#5]
I would like continuous integration set up for the boilerplate. 

- CI runs linting and unit tests
- Unit test coverage requirement is asserted in CI
- Readme references the state of the master's CI
- PR's require passing CI to merge

**Comment by faradayfan** [comment]
We still need to add this feature:
Readme references the state of the master's CI

**Comment by markamodo** [comment]
I added this in this PR
https://github.com/chgdev/express-service-template/pull/17
